### ISSUE TITLE
Run environment?

### ISSUE THREAD

**Issue by markubiak** [greenm01/porc#5]
Hello,
I'm trying to get this going with Anaconda2 v5.1.0. However, lots of stuff seems incorrect. For example, scipy.stats no longer has the nanstd function (afaik it never has) and nanstd is a numpy replacement. I can make a PR for that. One other thing that prevents me from executing is an issue creating IIR filters, it breaks on calling sig.butter:

```
Traceback (most recent call last):
  File "porc.py", line 374, in <module>
    main()  
  File "porc.py", line 371, in main
    roomcomp(args.impresp, args.filter, args.target, args.ntaps, args.mixed, args.opformat, args.trim, args.nsthresh, args.noplot)
  File "porc.py", line 152, in roomcomp
    Bf, Af = sig.butter(4, 30/(Fs/2), 'high')
  File "/opt/anaconda2/lib/python2.7/site-packages/scipy/signal/filter_design.py", line 2394, in butter
    output=output, ftype='butter')
  File "/opt/anaconda2/lib/python2.7/site-packages/scipy/signal/filter_design.py", line 1959, in iirfilter
    raise ValueError("Digital filter critical frequencies "
ValueError: Digital filter critical frequencies must be 0 < Wn < 1
```

I would really love to get mixed-phase filters on my system so if I can help I'd love to do so. I'm going to try to find the exact scipy version with nanstd and work from the Anaconda release that included it.

**Comment by markubiak** [comment]
Anaconda2 2.5 is working at the moment. The installer can be retrieved from https://repo.continuum.io/archive/
